apiVersion: v1
kind: Service
metadata:
  name: spotify-service
  namespace: spotify-app
  labels:
    app: spotify
spec:
  selector:
    app: spotify
  ports:
    - port: 1337
      targetPort: 1337
      name: socket
      protocol: TCP

  type: NodePort