apiVersion: v1
kind: Service
metadata:
  name: spotify-remastered
  namespace: spotify-app
spec:
  type: NodePort
  selector:
    app: spotify-remastered
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
      nodePort: 30008

